<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\Shared\Components\" />
    <Folder Include="wwwroot\files\img\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Intl.Realty.Firm.DataAccess\Intl.Realty.Firm.DataAccess.csproj" />
    <ProjectReference Include="..\Intl.Realty.Firm.Models\Intl.Realty.Firm.Models.csproj" />
    <ProjectReference Include="..\Intl.Realty.Firm.Utility\Intl.Realty.Firm.Utility.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.3.1" />
    <PackageReference Include="jQuery.Validation" Version="1.21.0" />
    <PackageReference Include="MailKit" Version="4.7.1.1" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MimeKit" Version="4.7.1" />
    <PackageReference Include="PdfiumViewer" Version="2.13.0" />
    <PackageReference Include="YamlDotNet" Version="16.1.0" />
  </ItemGroup>


  <ItemGroup>
    <Content Update="Views\Shared\Modal\_ConfirmSuccessModal.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
